version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2024.08
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker buildx build --build-arg REACT_APP_API_KEY=$REACT_APP_API_KEY \
              --build-arg REACT_APP_AUTH_DOMAIN=$REACT_APP_AUTH_DOMAIN \
              --build-arg REACT_APP_DATABASE_URL=$REACT_APP_DATABASE_URL \
              --build-arg REACT_APP_PROJECT_ID=$REACT_APP_PROJECT_ID \
              --build-arg REACT_APP_STORAGE_BUCKET=$REACT_APP_STORAGE_BUCKET \
              --build-arg REACT_APP_MESSAGING_SENDER_ID=$REACT_APP_MESSAGING_SENDER_ID \
              --build-arg REACT_APP_APP_ID=$REACT_APP_APP_ID \
              --build-arg REACT_APP_MEASUREMENT_ID=$REACT_APP_MEASUREMENT_ID \
              --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL \
              --build-arg VITE_API_BASE_NEW_URL=$VITE_API_BASE_NEW_URL \
              --build-arg VITE_CLIENT_ID=$VITE_CLIENT_ID \
              --build-arg VITE_CLIENT_SECRET=$VITE_CLIENT_SECRET \
              -t poweredu-frontend .

      - run:
          name: Tag Docker Image
          command: |
            docker tag poweredu-frontend aquariacore/poweredu-frontend:latest

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push aquariacore/poweredu-frontend:latest

      - run:
          name: Check and Install Docker on EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_DOMAIN "
              if ! command -v docker &> /dev/null; then
                echo 'Docker not found. Installing Docker...';
                sudo apt-get update;
                sudo apt-get install -y docker.io;
              else
                echo 'Docker is already installed.';
              fi
            "

      - run:
          name: Stop Running Container on EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_DOMAIN "
              sudo docker stop poweredu-frontend || true;
              sudo docker rm poweredu-frontend || true
            "

      - run:
          name: Pull Latest Docker Image on EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_DOMAIN "
              sudo docker pull aquariacore/poweredu-frontend:latest
            "

      - run:
          name: Deleting Older Images from EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_DOMAIN "
              sudo docker images --filter=reference='aquariacore/poweredu-frontend:*' --format '{{.ID}}' | grep -v "$(sudo docker images --filter=reference='aquariacore/poweredu-frontend:latest' --format '{{.ID}}')" | xargs -r sudo docker rmi
            "

      - run:
          name: Run Updated Docker Container on EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_DOMAIN "
              sudo docker run --network host -d --name poweredu-frontend aquariacore/poweredu-frontend:latest
            "

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build