// File to store all the theme colors 

const themes = {
     SoberViolet: {
       primaryColor: "#6A0DAD",
       secondaryColor: "#D8BFD8",
       normal1: "#6A0DAD",
       normal2: "#6A0DAD",
        normal3: "#6A0DAD",
        background: "#F8F8FF",
        textColor: "#FFF",
        textColorAlt: "#000000",
        sideBarColor: "#D8BFD8",
        googleMeetButton: "#6A0DAD",
        inputBackground: "#FFF",
        inputTextColor: "#000000",
        logoutColor: "red",
        sideBarButton: "#6A0DAD",
        borderColor: "#D8BFD8",
        boxBackground: "#F8F8FF",
        boxTextColor: "#000000",
        toastColor: "#6A0DAD",
        toastTextColor: "#FFFFFF",
        boxHoverColor: "#E6E6FA",
        boxHoverTextColor: "#000000",
     },
     ColdCrust: {
       primaryColor: "#457B9D",
       secondaryColor: "#A8DADC",
       normal1: "#457B9D",
       normal2: "#1D3557",
       normal3: "#457B9D",
      background: "#FFF",
      textColor: "#FFF",
      textColorAlt: "#000000",
      sideBarColor: "#A8DADC",
      sideBarButton: "#457B9D",
      sideBarCollapseButton: "#FFF",
      googleMeetButton: "#457B9D",
      inputBackground: "#FFF",
      inputTextColor: "#000000",
      logoutColor: "red",
      borderColor: "#A8DADC",
      boxBackground: "#FFF",
      boxBlurBackground: "rgba(255, 255, 255, 1)",
      boxTextColor: "#000000",
      toastColor: "#457B9D",
      toastTextColor: "#FFFFFF",
      boxHoverColor: "#E0F7FA",
      boxHoverTextColor: "#000000",
      scrollColor: "#ff9a9a", 
     },

    Ocean: {
      primaryColor: "#143e7c",
      secondaryColor: "#143e7c",
      normal1: "#051937",
      normal2: "#143e7c",
      normal3: "#143e7c",
      background: "#FFF",
      textColor: "#FFFFFF",
      textColorAlt: "#000000",
      sideBarColor: "#051937",
      googleMeetButton: "#143e7c",
      inputBackground: "#F8F8FF",
      inputTextColor: "#000000",
      logoutColor: "red",
      sideBarButton: "#143e7c",
      borderColor: "#143e7c",
      boxBackground: "#FFF",
      boxTextColor: "#000000",
      toastColor: "#143e7c",
      toastTextColor: "#FFFFFF",
      boxHoverColor: "#e9edff",
      boxHoverTextColor: "#000000",
      
    },

    OceanBreeze: {
      primaryColor: "#ae1dc4",
      secondaryColor: "linear-gradient(135deg, #b2b8ff 0%, #fae6eb 150%)",
      normal1: "#b2b8ff",
      normal2: "#7978E9",
      normal3: "#c96bff",
      background: "#FFF",
      textColor: "#FFFFFF",
      textColorAlt: "#000000",
      textColorLight: "#000000",
      sideBarColor: "linear-gradient(135deg, #b2b8ff 0%, #fae6eb 150%)",
      sideBarButton : "#ae1dc4",
      borderColor : "#b2b8ff",
      googleMeetButton : "#9694FF",
      inputBackground: "#FFF",
      inputTextColor: "#000000",
      logoutColor: "red",
      boxBackground:"#FFF",
      boxTextColor:"#000000",
      toastColor : "#e9cffb",
      boxHoverColor : "#e9cffb",
      boxHoverTextColor : "#000000",

    } , 



    DarkMode: {
      primaryColor: "#E63946",
      secondaryColor: "#1D3557",    
      normal1: "#A8DADC",           
      normal2: "#457B9D",           
      normal3: "#F4A261",           
      background: "#121212",        
      textColor: "#EDEDED",         
      textColorAlt: "#A8A8A8",      
      textColorLight: "#ffffffdc",    
      hoverColor: "#2A2A2A",        
      googleMeetButton: "#E63946",  
      inputBackground: "#1E1E1E",   
      inputTextColor: "#FFFFFF",    
      logoutColor: "#FF5252",       
      sideBarColor: "#000",      
      sideBarButton: "#2A2A2A",
      sideBarCollapseButton: "#FFF",     
      borderColor: "#393E46",       
      boxBackground: "#1C1C1C",  
      boxTextColor: "#F0F0F0",      
      toastColor: "#FF9F1C",        
      boxHoverColor: "#2E2E2E",     
      boxHoverTextColor: "#FFFFFF", 
     scrollColor: "#ff9a9a", 
    },
    

   };
   
   export default themes;
