// File to store all the theme colors

const themes = {
  "Dark Blue": {
    specialColor: "#00369a",
    normal1: "#6A0DAD",
    normal2: "#6A0DAD",
    normal3: "#6A0DAD",
    background: "#070F2B",
    backgroundRight: "#f7fcff",
    boxBackgroundTop: "#001b5f",
    boxBackgroundSolid: "#FFF",
    buttonColor: "#001b5f",
    textColor: "#000",
    textColorAlt: "#FFF",
    textColorLight: "#4b4b4b",
    sideBarColor: "#070F2B",
    googleMeetButton: "#6A0DAD",
    inputBackground: "#FFF",
    inputTextColor: "#000000",
    logoutColor: "red",
    sideBarButton: "#9290C3",
    sideBarText: "#FFF",
    sideBarCollapseButton: "#FFF",
    borderColor: "#e2e2e2",
    toastColor: "#6A0DAD",
    toastTextColor: "#FFFFFF",
    boxBackground: "#FFF",
    boxTextColor: "#000000",
    boxHoverColor: "#E6E6FA",
    boxHoverTextColor: "#000000",
    scrollColor: "#ff9a9a",
    drawerClose: "#6A0DAD",
  },


  "Ocean Breeze": {
    specialColor: "#b2b8ff",
    normal1: "#b2b8ff",
    normal2: "#7978E9",
    normal3: "#c96bff",
    background: "linear-gradient(135deg, #fae6eb 0%, #b2b8ff 30%)",
    backgroundRight: "#ffffffa2",
    boxBackgroundTop: "#b2b8ff",
    boxBackgroundSolid : "#ffffff",
    buttonColor: "#b2b8ff",
    textColor: "#000",
    textColorAlt: "#FFF",
    textColorLight: "#000000",
    sideBarColor: "transparent",
    sideBarButton: "#ae1dc4",
    sideBarText: "#FFF",
    sideBarCollapseButton: "#FFF",
    borderColor: "#FFF ",
    googleMeetButton: "#9694FF",
    inputBackground: "#FFF",
    inputTextColor: "#000000",
    logoutColor: "red",
    boxBackground: "#ffffff7f",
    boxTextColor: "#000000",
    toastColor: "#e9cffb",
    toastTextColor: "#000000",
    boxHoverColor: "#e9cffb",
    boxHoverTextColor: "#000000",
    scrollColor: "#ff9a9a",
    drawerClose: "#b2b8ff",
    
  },
};

export default themes;
