// File to store all the theme colors

const themes = {
  "Dark Blue": {
    specialColor: "#00369a",
    normal1: "#00369a",
    normal2: "#0072ce",
    normal3: "#00a8e8",
    background: "#070F2B",
    backgroundRight: "#f7fcff",
    boxBackgroundTop: "#00369a",
    boxBackgroundSolid: "#FFF",
    buttonColor: "#001b5f",
    textColor: "#000",
    textColorAlt: "#FFF",
    textColorLight: "#4b4b4b",
    sideBarColor: "#070F2B",
    inputBackground: "#FFF",
    inputTextColor: "#000000",
    logoutColor: "red",
    sideBarButton: "#9290C3",
    sideBarText: "#FFF",
    sideBarCollapseButton: "#00369a",
    borderColor: "#e9f7ff",
    borderColorLight: "#d4d4d4",
    toastColor: "#6A0DAD",
    toastTextColor: "#FFFFFF",
    boxBackground: "#FFF",
    boxTextColor: "#000000",
    boxHoverColor: "#E6E6FA",
    boxHoverTextColor: "#000000",
    scrollColor: "#ff9a9a",
    drawerClose: "#001b5f",
  },


  "Ocean Breeze": {
    specialColor: "#b2b8ff",
    normal1: "#b2b8ff",
    normal2: "#7978E9",
    normal3: "#c96bff",
    background: "linear-gradient(135deg, #fae6eb 0%, #b2b8ff 30%)",
    backgroundRight: "#fffffff3",
    boxBackgroundTop: "#b2b8ff",
    boxBackgroundSolid : "#ffffff",
    buttonColor: "#b2b8ff",
    textColor: "#000",
    textColorAlt: "#FFF",
    textColorLight: "#000000",
    sideBarColor: "transparent",
    sideBarButton: "#ae1dc4",
    sideBarText: "#FFF",
    sideBarCollapseButton: "#FFF",
    borderColor: "#FFF", 
    inputBackground: "#FFF",
    inputTextColor: "#000000",
    logoutColor: "red",
    boxBackground: "#ffffff7f",
    boxTextColor: "#000000",
    toastColor: "#e9cffb",
    toastTextColor: "#000000",
    boxHoverColor: "#e9cffb",
    boxHoverTextColor: "#000000",
    scrollColor: "#ff9a9a",
    drawerClose: "#b2b8ff",
    
  },

  "Sunset Glow": {
    specialColor: "#ff4500",
    normal1: "#ff6347",
    normal2: "#ff7f50",
    normal3: "#ff8c00",
    background: "#ffefd5",
    backgroundRight: "#ffe4b5",
    boxBackgroundTop: "#ffdead",
    boxBackgroundSolid: "#fff5ee",
    buttonColor: "#ff4500",
    textColor: "#000",
    textColorAlt: "#FFF",
    textColorLight: "#4b4b4b",
    sideBarColor: "#ffefd5",
    googleMeetButton: "#ff6347",
    inputBackground: "#FFF",
    inputTextColor: "#000000",
    logoutColor: "red",
    sideBarButton: "#ff7f50",
    sideBarText: "#FFF",
    sideBarCollapseButton: "#FFF",
    borderColor: "#e2e2e2",
    toastColor: "#ff8c00",
    toastTextColor: "#FFFFFF",
    boxBackground: "#FFF",
    boxTextColor: "#000000",
    boxHoverColor: "#ffe4b5",
    boxHoverTextColor: "#000000",
    scrollColor: "#ff4500",
    drawerClose: "#ff6347",
  },

"Forest Green": {
  "specialColor": "#006400",
  "normal1": "#228B22",
  "normal2": "#2E8B57",
  "normal3": "#3CB371",
  "background": "url(https://cdn.vectorstock.com/i/500p/04/50/abstract-liquid-gradient-background-fluid-green-vector-53440450.jpg) no-repeat center center ",
  "backgroundRight": "#f6f6f61c",
  "boxBackgroundTop": "#90EE90",
  "boxBackgroundSolid": "#FFF",
  "buttonColor": "#006400",
  "textColor": "#000000",
  "textColorAlt": "#FFFFFF",
  "textColorLight": "#333333",
  "sideBarColor": "transparent",
  "sideBarButton": "#228B22",
  "sideBarText": "#FFFFFF",
  "sideBarCollapseButton": "#FFF",
  "googleMeetButton": "#228B22",
  "inputBackground": "#FFFFFF",
  "inputTextColor": "#000000",
  "logoutColor": "#FF4500",
  "borderColor": "#BDBDBD",
  "toastColor": "#006400",
  "toastTextColor": "#FFFFFF",
  "boxBackground": "#E6FFE6",
  "boxTextColor": "#000000",
  "boxHoverColor": "#D0FFD0",
  "boxHoverTextColor": "#000000",
  "scrollColor": "#228B22",
  "drawerClose": "#006400"
},
  "Midnight Purple": {
      specialColor: "#845ec2", 
      normal1: "#d65db1", 
      normal2: "#ff6f91", 
      normal3: "#ff9671", 
      background: "linear-gradient( 45deg, #845ec2 20%, #d65db1 40%, #ff6f91 60%, #ff9671 80%, #ffc75f 100%, #f9f871 110%)",
      backgroundRight: "#ffffffd8",
      boxBackgroundTop: "#845ec2", 
      boxBackgroundSolid: "#FFF", 
      buttonColor: "#845ec2", 
      textColor: "#000",
      textColorAlt: "#FFF",
      textColorLight: "#4b4b4b",
      sideBarColor: "transparent",
      googleMeetButton: "#d65db1", 
      inputBackground: "#FFF",
      inputTextColor: "#000000",
      logoutColor: "red",
      sideBarButton: "#f93475", 
      sideBarText: "#FFF",
      sideBarCollapseButton: "#845ec2",
      borderColor: "#fff3ea",
      toastColor: "#ff9671", 
      toastTextColor: "#FFFFFF",
      boxBackground: "#FFF",
      boxTextColor: "#000000",
      boxHoverColor: "#e6e6fa",
      boxHoverTextColor: "#000000",
      scrollColor: "#845ec2", 
      drawerClose: "#d65db1", 
      lightColor : "#fffcff"
    },
  "Midnight Orange": {
    specialColor: "#1E3E62",
    normal1: "#ff6347",
    normal2: "#ff7f50",
    normal3: "#ff8c00",
    background: "#000",
    backgroundRight: "#FFF",
    boxBackgroundTop: "#FF6500",
    boxBackgroundSolid: "#FFF",
    buttonColor: "#ff4500",
    textColor: "#000",
    textColorAlt: "#FFF",
    textColorLight: "#4b4b4b",
    sideBarColor: "transparent",
    googleMeetButton: "#ff6347",
    inputBackground: "#FFF",
    inputTextColor: "#000000",
    logoutColor: "red",
    sideBarButton: "#ff7f50",
    sideBarText: "#FFF",
    sideBarCollapseButton: "#FFF",
    borderColor: "#e2e2e2",
    toastColor: "#ff8c00",
    toastTextColor: "#FFFFFF",
    boxBackground: "#FFF",
    boxTextColor: "#000000",
    boxHoverColor: "#a6a6a6",
    boxHoverTextColor: "#000000",
    scrollColor: "#ff4500",
    drawerClose: "#ff6347",
  },
};

export default themes;

